[package]
name = "bevy_renet"
version = "0.0.3"
keywords = ["gamedev", "networking"]
description = "Bevy plugin for the renet crate: Server/Client network library for multiplayer games"
repository = "https://github.com/lucaspoffo/renet"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.0-dev", git = "https://github.com/bevyengine/bevy", default-features = false }
renet = { path = "../renet", version = "0.0.8" }

[dev-dependencies]
serde = { version = "1.0", features = [ "derive" ] } 
bevy = { version = "0.8.0-dev", git = "https://github.com/bevyengine/bevy", default-features = false, features = ["bevy_core_pipeline", "bevy_render", "bevy_pbr", "x11"] }
bincode = "1.3.1"
